[project]
name = "backend"
version = "0.1.0"
description = "FastAPI backend"
requires-python = ">=3.10"
dependencies = [
    "fastapi",
    "uvicorn",
    "pydantic",
    "python-dotenv",
    "authlib",
    "httpx",
    "groq",
    "resend",
    "itsdangerous"
]

[tool.vercel]
entrypoint = "api:app"